- name: ensure database is created
  become_user: postgres
  vars:
      ansible_ssh_pipelining: true
  postgresql_db:
    name: "asu"

- name: ensure user has access to database
  become_user: postgres
  vars:
      ansible_ssh_pipelining: true
  postgresql_user:
    db: "asu"
    name: "{{ database_user }}"
    password: "{{ database_pass }}"
    priv: ALL

- name: ensure user does not have unnecessary privilege
  become_user: postgres
  vars:
      ansible_ssh_pipelining: true
  postgresql_user:
    name: "{{ database_user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB

- name: init database
  become_user: postgres
  vars:
      ansible_ssh_pipelining: true
  postgresql_db:
    name: "asu"
    state: restore
    target: "{{ server_dir }}/asu/utils/tables.sql"
