- name: install required software
  package: name={{ item }} state=present
  with_items:
    - nginx
    - postgresql
    - odbc-postgresql
    - python3-pyodbc
    - python3-psycopg2
    - python3-gnupg
    - python-psycopg2
    - python3-yaml
    - python3-flask
    - git

- name: install imagebuilder dependencies
  package: name={{ item }} state=present
  with_items:
    - subversion
    - build-essential
    - libncurses5-dev
    - zlib1g-dev
    - gawk
    - git
    - ccache
    - gettext
    - libssl-dev
    - xsltproc
    - wget
    - unzip
    - python

- name: clone git repository
  git:
    repo: 'https://github.com/aparcar/gsoc17-attended-sysupgrade.git'
    dest: "{{ server_folder }}"
    clone: yes
    update: yes

- name: ensure database is created
  become_user: postgres
  postgresql_db:
    name: "{{ database_name }}"

- name: ensure user has access to database
  become_user: postgres
  postgresql_user:
    db: "{{ database_name }}"
    name: "{{ database_user }}"
    password: "{{ database_pass }}"
    priv: ALL

- name: ensure user does not have unnecessary privilege
  become_user: postgres
  postgresql_user:
    name: "{{ database_user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB

- name: copy nginx server config
  template: src=server.conf dest=/etc/nginx/sites-enabled/server.conf

- name: copy server service
  template:
    src: server.service
    dest: /etc/systemd/system/server.service

- name: copy config.yml
  template: src=config.yml dest="{{ server_folder }}/config.yml"

- name: start and enable server
  service:
    name: server
    state: started
    enabled: true

- name: init server
  become_user: "{{ server_user }}"
  command: python3 cli.py -ia # download all releases and init all current imagebuilders
  args:
    chdir: "{{ server_folder }}"

