language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install flake8 pytest
# command to run tests
script:
  - flake8 --exclude=asu/__init__.py
  - pytest --cov=asu
