language: python

python:
  - "3.6"

services:
  - postgresql

install:
  - pip install flake8 pytest

before_script:
  - psql -c 'create database asu;' -U postgres

script:
  - pip install -e .
  - flake8 --exclude=asu/__init__.py
  - pytest -c pytest.ini
