language: python

addons:
  apt:
    packages:
    - odbc-postgresql
    - unixodbc-dev

python:
  - "3.6"

services:
  - postgresql

install:
  - pip install flake8 pytest

before_script:
  - psql -c "CREATE DATABASE asu;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'changeme';" -U postgres
  - psql asu < ./asu/utils/tables.sql -U postgres

script:
  - pip install -e .
  - flake8 --exclude=asu/__init__.py
  - pytest -c pytest.ini
