version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: attendedsysupgrade

  server:
    build: .
    entrypoint:
      - "gunicorn"
      - "asu:app"
  worker:
    build: .
    entrypoint:
      - "python3"
      - "worker.py"
