version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: asu

  server:
    build: .
    entrypoint:
      - "gunicorn3"
      - "asu:app"
    ports:
      - 5000

  worker:
    build: .
    entrypoint:
      - "python3"
      - "worker.py"
