version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: asu
    volumes:
      - "./asu/utils/tables.sql:/docker-entrypoint-initdb.d/tables.sql"

  server:
    build: .
    command: sh -c './.wait-for db:5432 -- python3 cli.py -i &&  gunicorn3 asu:app'
    volumes:
      - "./config.yml:/asu/config.yml"
    ports:
      - 5000
    depends_on:
      - db

  worker:
    build: .
    command: sh -c './.wait-for server:5000 -t 300 -- python3 worker.py'
    volumes:
      - "./config.yml:/asu/config.yml"
    depends_on:
      - db
