version: "3.5"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: asu
      POSTGRES_USER: asu
    volumes:
      - "./asu/utils/tables.sql:/docker-entrypoint-initdb.d/tables.sql"

  server:
    build: .
    environment:
      - FLASK_APP=asu
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    command: sh -c 'sh .wait-for db:5432 -- flask loaddb && gunicorn3 -b 0.0.0.0:8000 asu:app'
    volumes:
      - "./config.yml:/asu/config.yml"
    ports:
      - 8000
    depends_on:
      - db

  worker:
    build: .
    environment:
      - FLASK_APP=asu
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    command: sh -c 'sh .wait-for server:8000 -t 300 -- flask run-worker'
    volumes:
      - "./config.yml:/asu/config.yml"
      - "./worker/:/asu/worker/"
      - "./updater/:/asu/updater/"
    depends_on:
      - db
