version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: asu
    volumes:
      - "./asu/utils/tables.sql:/docker-entrypoint-initdb.d/tables.sql"

  server:
    build: .
    environment:
      - FLASK_APP=asu
    command: sh -c './.wait-for db:5432 -- flask fetch-targets && gunicorn3 -b 0.0.0.0:8000 asu:app'
    volumes:
      - "./config.yml.docker:/asu/config.yml"
    ports:
      - 8000
    depends_on:
      - db

  worker:
    build: .
    command: sh -c './.wait-for server:8000 -t 300 -- python3 worker.py'
    volumes:
      - "./config.yml.docker:/asu/config.yml"
      - "./worker/:/asu/worker/"
      - "./updater/:/asu/updater/"
    depends_on:
      - db
