- name: install required software
  package: name={{ item }} state=present
  with_items:
    - nginx
    - postgresql
    - odbc-postgresql
    - python3-pyodbc
    - python3-psycopg2
    - python-psycopg2
    - python3-yaml
    - python3-flask
    - git

- name: clone git repository
  git:
    repo: 'https://github.com/aparcar/gsoc17-attended-sysupgrade.git'
    dest: /srv/
    clone: yes
    update: yes

- name: ensure database is created
  become_user: postgres
  postgresql_db:
    name: "attended-sysupgrade"

- name: ensure user has access to database
  become_user: postgres
  postgresql_user:
    db: "attended-sysupgrade"
    name: "postgresql"
    password: "{{ db_pass }}"
    priv: ALL 

- name: ensure user does not have unnecessary privilege
  become_user: postgres
  postgresql_user: 
    name: "postgresql"
    role_attr_flags: NOSUPERUSER,NOCREATEDB

- name: copy nginx default page
  copy: src=nginx_default dest=/etc/nginx/sites-enabled/default
