- name: install required software
  package: name={{ item }} state=present
  with_items:
    - nginx
    - postgresql
    - odbc-postgresql
    - python3-pyodbc
    - python3-psycopg2
    - python3-gnupg
    - python-psycopg2
    - python3-yaml
    - python3-flask
    - git

- name: install imagebuilder dependencies
  package: name={{ item }} state=present
  with_items:
    - subversion
    - build-essential
    - libncurses5-dev
    - zlib1g-dev
    - gawk
    - git
    - ccache
    - gettext
    - libssl-dev
    - xsltproc
    - wget
    - unzip
    - python

- name: clone git repository
  git:
    repo: 'https://github.com/aparcar/gsoc17-attended-sysupgrade.git'
    dest: /srv/
    clone: yes
    update: yes

- name: ensure database is created
  become_user: postgres
  postgresql_db:
    name: "attended-sysupgrade"

- name: ensure user has access to database
  become_user: postgres
  postgresql_user:
    db: "attended-sysupgrade"
    name: "postgresql"
    password: "{{ db_pass }}"
    priv: ALL

- name: ensure user does not have unnecessary privilege
  become_user: postgres
  postgresql_user:
    name: "postgresql"
    role_attr_flags: NOSUPERUSER,NOCREATEDB

- name: copy nginx default page
  copy: src=nginx_default dest=/etc/nginx/sites-enabled/default

- name: copy server service
  template:
    src: update-server.service
    dest: /etc/systemd/system/update-server.service

- name: start and enable server
  service:
    name: update-server
    state: started
    enabled: true

- name: copy worker service
  template:
    src: update-worker.service
    dest: /etc/systemd/system/update-worker.service

- name: start and enable worker
  service:
    name: update-worker
    state: started
    enabled: true

- name: copy snapshot flush service
  template:
    src: snapshot-flush.service
    dest: /etc/systemd/system/snapshot-flush.service

- name: copy snapshot flush timer
  copy:
    src: snapshot-flush.timer
    dest: /etc/systemd/system/snapshot-flush.timer

- name: start and enable snapshot flush timer
  service:
    name: snapshot-flush.timer
    state: started
    enabled: true

- name: copy worker restart service
  template:
    src: worker-restart.service
    dest: /etc/systemd/system/worker-restart.service

- name: copy worker restarth timer
  copy:
    src: worker-restart.timer
    dest: /etc/systemd/system/worker-restart.timer

- name: start and enable worker restart timer
  service:
    name: worker-restart.timer
    state: started
    enabled: true

- name: create cronjob to remove snapshots at midnight
  cron:
   name: "remove snapshots at midnight"
   minute: "0"
   hour: "0"
   job: "cd /srv/update-server/ && python3 cli.py -f"
  become: yes
  become_user: "{{ update_server_user }}"

