- name: install required software
  package: name={{ item }} state=present
  with_items:
    - postgresql
    - odbc-postgresql
    - python3-pyodbc
    - python3-psycopg2
    - python3-gnupg
    - python-psycopg2
    - python3-yaml
    - git

- name: install imagebuilder dependencies
  package: name={{ item }} state=present
  with_items:
    - subversion
    - build-essential
    - libncurses5-dev
    - zlib1g-dev
    - gawk
    - git
    - ccache
    - gettext
    - libssl-dev
    - xsltproc
    - wget
    - unzip
    - python

- name: clone git repository
  git:
    repo: 'https://github.com/aparcar/gsoc17-attended-sysupgrade.git'
    dest: "{{ worker_folder }}"
    clone: yes
    update: yes

- name: copy worker service
  template:
    src: worker.service
    dest: /etc/systemd/system/worker.service

- name: start and enable worker
  service:
    name: worker
    state: started
    enabled: true
